spring:
  datasource:
    url: jdbc:mysql://31.97.239.83:3306/demo?useSSL=false&serverTimezone=UTC
    username: root
    password: Javadeveloper@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  spring:
  thymeleaf:
    cache: false
